### ISSUE TITLE
BUG: When one tries to access a non-existing variable label  the value labels are returned 

### ISSUE THREAD

**Issue by gbiele** [hadley/haven#108]
When haven reads SPSS/sav files it also reads in variable labels and value labels to construct a vector of the class labelled, where the variable label is stored in attributes(foo)$label and the variable labels are stored in attributes(foo)$labels.

This distinction breaks down if the labelled vector has only value labels but not variable label. In this case, haven will return the value labels when it is asked for the variable label with attributes(foo)$label or attr(foo,"label") and only correctly return NULL with attributes(foo)[["label"]].

Maybe there is something I don't know about how one should access entries in a list, but it seems wrong to me that 2 out of 3 attempts to access a variable attribute return incorrect results.
[As an aside, using label and labels as names for the attributes invites to making mistakes. 
variable_label and value_labels are longer, but seem safe to me.]

Short reproducible example:
s2 <- labelled(c(1, 1, 2), c(Male = 1, Female = 2))
attributes(s2)
returns
"
$labels
  Male Female 
     1      2 

$class
[1] "labelled"
"

and

attr(s2,"labels")
returns
"
  Male Female 
     1      2 
"
so far, so good.

However, 
attr(s2,"label")
and 
attributes(s2)$label
both returns
"
  Male Female 
     1      2 
"

but 
attributes(s2)[["label"]]
correctly returns
"
NULL
"

sessionInfo()
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Norwegian (Bokmål)_Norway.1252 
[2] LC_CTYPE=Norwegian (Bokmål)_Norway.1252   
[3] LC_MONETARY=Norwegian (Bokmål)_Norway.1252
[4] LC_NUMERIC=C                              
[5] LC_TIME=Norwegian (Bokmål)_Norway.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] haven_0.2.0

loaded via a namespace (and not attached):
[1] Rcpp_0.12.0

**Comment by gergness** [comment]
I think this is just an oddity of R (and one that's bitten me before!). See the `exact` argument in ?attr and ?\`[[\`. `$` and `attr()` have exact = FALSE as their default, while `[[` has exact = TRUE. 

So these three are equivalent:
```
s2 <- labelled(c(1, 1, 2), c(Male = 1, Female = 2))

attr(s2, "label")
#>   Male Female 
#>      1      2
attributes(s2)$label
#>   Male Female 
#>      1      2
attributes(s2)[["label", exact = FALSE]]
#>   Male Female 
#>      1      2
```

As are these two:
```
attr(s2, "label", exact = TRUE)
#> NULL
attributes(s2)[["label"]]
#> NULL
```

Note that this is true for all lists (including data.frames). 
```
df <- data.frame(x_has_a_really_long_name = 1)
df$x
#> [1] 1
df[["x"]]
#> NULL
df[["x", exact = FALSE]]
#> [1] 1
```

And to add to the confusion, if there are multiple matches, they all return NULL again.
```
df <- data.frame(x_has_a_really_long_name = 1, x2 = 2)
df$x
#> NULL
df[["x"]]
#> NULL
df[["x", exact = FALSE]]
#> NULL
```

So it's a "feature" because it allows for less typing in interactive mode, but I think that it can make debugging code difficult. If you don't want the partial matching, I think the best thing to do is to use `[[` exclusively instead of `$`. There's also some discussion here: http://adv-r.had.co.nz/Subsetting.html ($ section)

**Comment by sjPlot** [comment]
You may take a look at the `get_labels` resp `get_label` functions in the [sjmisc-package](http://cran.r-project.org/package=sjmisc).

See an introduction for working with labelled data [here](http://strengejacke.de/sjPlot/sjmisc/)
