### ISSUE TITLE
Stata supports only labelled integers

### ISSUE THREAD

**Issue by hadley** [hadley/haven#169]
And labels can be at most 32 characters long

**Comment by evanmiller** [comment]
I think you mean Stata?

**Comment by hadley** [comment]
Doh, yes

**Comment by brianstamper** [comment]
I believe the limitation on label lengths is not correct - the length of _the name of a set of value labels_ is max 32, but the value labels themselves are limited to 32,000 characters each. Discovered this by read_dta() data that had been written by Stata and subsequently not being able to write_dta() because of this limit.

**Comment by hadley** [comment]
@brianstamper Can you please file a new issue with a reproducible example?

**Comment by brianstamper** [comment]
@hadley Filed here https://github.com/tidyverse/haven/issues/259. Thank you!
