### ISSUE TITLE
SAS datasets that are compressed generate error using Haven (and also sas7bdat)

### ISSUE THREAD

**Issue by dramage1** [hadley/haven#18]
I encountered an error when trying to read a SAS dataset that was compressed. I was wondering if there are  plans to address this?  I had to use PC SAS to uncompress the file before I could get it to work. Relevant log is below:

> library(haven)
> library(sas7bdat)
> 
> sessionInfo()
R version 3.1.2 (2014-10-31)
Platform: x86_64-w64-mingw32/x64 (64-bit)

other attached packages:
[1] sas7bdat_0.5     dplyr_0.4.1      haven_0.0.0.9000

> ds.unix.fmt <- read_sas("C:/0_data/GOES/ORACLE/rd_frmae.sas7bdat")
Error: Failed to parse C:\0_data\GOES\ORACLE\rd_frmae.sas7bdat: A row in the file was not the expected length.
> 
> ds_unix.fmt1 <- read.sas7bdat("C:/0_data/GOES/ORACLE/rd_frmae.sas7bdat")
Error in read.sas7bdat("C:/0_data/GOES/ORACLE/rd_frmae.sas7bdat") : 
  file contains compressed data

> ds.pc.fmt <- read_sas("C:/0_data/GOES/DATASETS/rd_frmae.sas7bdat")
>

**Comment by evanmiller** [comment]
The haven and sas7bdat packages currently do not support binary compression; see here for a discussion and possible workaround:

https://github.com/BioStatMatt/sas7bdat/issues/5

**Comment by dramage1** [comment]
Thanks Evan for letting me know.

**Comment by dramage1** [comment]
FYI, after much travail getting Java issues resolved (library sas7bdat.parso  needs Java 7 and also need a Java SDK, I was able to get things to work. It would be nice not to have to go through all these steps.

**Comment by BioStatMatt** [comment]
The sas7bdat.parso library wraps the "Parso" Java library. The R interface depends on the rJava package, which imposes the dependencies that you mention. Thus, the difficulty in installing sas7bdat.parso is primarily due to the difficulty in installing rJava, which is partly why I haven't uploaded this package to CRAN (I also don't want to maintain another package, especially with an rJava dependency).

However, you've highlighted a important point, that the Parso library reads both "CHAR", and "BINARY" compressed sas7bdat files. As far as I know, Parso is the only open source package that implements the latter. In fact, the details of "BINARY" compression is a major hole in the sas7bdat documentation (https://github.com/BioStatMatt/sas7bdat/blob/master/vignettes/sas7bdat.rst). Of course, all that is necessary to fill this hole is to read through the Parso source code and write down what it does with "BINARY" compressed files. I have plans to do that, but I would gratefully accept the help of anyone willing to tackle this problem.

**Comment by evanmiller** [comment]
It's worth noting that the Parso library is dual-licensed under GPLv3 and an "ask us" commercial license. That essentially makes it toxic for ReadStat, which is MIT-licensed.

IANAL but if @BioStatMatt reads the Parso source code it may force his own code into GPLv3. You can't copyright facts, so the legal status of the vignette should remain the same, however.

**Comment by evanmiller** [comment]
It looks like the Python sas7bdat package also supports binary compression, with the added benefit that it's MIT licensed:

https://pypi.python.org/pypi/sas7bdat
