### ISSUE TITLE
writing dates to sav 

### ISSUE THREAD

**Issue by afleishman** [hadley/haven#25]
I am unable to write dates using the haven package. I've tried formatting the dates as dates, POSIX, and character types. Any ideas?

>library("haven")
>
>id <- c(1, 2, 3)
>date <- as.Date(c("2014-09-23", "2014-09-24", "2014-09-25"))
>date.pos <- as.POSIXct(date)
>date.char <- as.character(date)
>write_sav(data.frame(id, date, date.pos, date.char), "test.sav")

![data view](https://cloud.githubusercontent.com/assets/6239089/6399438/7c563944-bdc0-11e4-8d5e-7d538c837b2e.png)
![variable view](https://cloud.githubusercontent.com/assets/6239089/6399439/7c5681a6-bdc0-11e4-87e9-d6126cef1c2a.png)

**Comment by hadley** [comment]
Haven currently doesn't have any support for date/times on either input or output :(

**Comment by afleishman** [comment]
I sort of guessed this was the case. Converting dates to different pieces of software is quite unnerving!

Thanks for the quick response.

**Comment by hadley** [comment]
No need to close, I'll work on eventually and this will remind me that I need to do it.

**Comment by afleishman** [comment]
Oh, great. Thanks so much!

**Comment by evanmiller** [comment]
@hadley to convert POSIX timestamps I think all you need to do is add the # of seconds between 10/14/1582 and 1/1/1970, then supply "DATE" or "DATETIME" as the format.

**Comment by hadley** [comment]
@evanmiller thanks! Also need to re-look at our email thread on reading dates

**Comment by afleishman** [comment]
When I export Date vector from R to SPSS it gives me the number of days between the date and January 1, 1970. I can write very simple syntax in SPSS to correct this. Figured this tidbit may help on your end!

If you look at the screenshot above, you will see the first case in the "date" variable is 16336. January 1, 1970 + 16336 days = September 23, 2014!

**Comment by larmarange** [comment]
The issue is similar when exporting to Stata.

It seems that when **haven** is exporting to SPSS or Stata, no format are exported. Therefore, the software (SPSS or Stata) don't know that this numerical variable should be considered as a date.

**Comment by huftis** [comment]
Note that SPSS does not support time zones *or* daylight saving time. R does, so the following results in the correct answer (23 hours instead of 24 hours) (in my default time zone):

> start = as.POSIXct("2015-03-28 07:00")
> end = as.POSIXct("2015-03-29 07:00")
> start
[1] "2015-03-28 07:00:00 CET"
> end
[1] "2015-03-29 07:00:00 CEST"
> end-start
Time difference of 23 hours

Because the times may be used for calculations after exporting to SPSS, I think it’s better to save all date-times as *UTC* date-times. Here’s a function that can be used (for `POSIXct` objects):

    dt2spss = function(x)
      as.numeric(x) - as.numeric(as.POSIXct("1582-10-14", tz="UTC"))
    # same as `as.numeric(x) + 12219379200`, which is faster

This converts the date-time into the number of seconds sincce 1582-10-14, i.e. the internal format SPSS uses for all date-times (and dates). Any calculations done in SPSS would then work correctly. Example:

    > (dt2spss(end) - dt2spss(start))/60/60
    [1] 23

For dates, the following should do the trick:

    d2spss = function(x)
      (as.numeric(x) - as.numeric(as.Date("1582-10-14")))*24*60*60
    # same as `86400 * (as.numeric(x) + 141428)`, which is faster

Having an *option* for saving the date-times in ‘local time’ would also be nice, for applications where one only wants to *see* a date-time in SPSS, not doing any calculations on them (or only doing within-day day-time calculations, e.g. calculating hours worked). This can be accomplished by `force_tz(x, "UTC")` before calling `dt2spss()` above.

**Comment by hadley** [comment]
@huftis all date times in R are stored as number of seconds since unix epoch - time zones only affect how the times are displayed

**Comment by huftis** [comment]
@hadley Yes, I know. Did I write anything that implied something else?

**Comment by hadley** [comment]
It was your comment "I think it’s better to save all date-times as UTC date-times" that threw me off because in R all date-times are in UTC.
